### ISSUE TITLE
Handle crashes from error code 503

### ISSUE THREAD

**Issue by slvwolf** [slvwolf/panasonic-comfort-cloud-mqtt#14]
System will crash if encountering error code 503 for a long period of time
 
```
2022-09-20 01:01:50,360 - Service - WARNING - Sequence of errors detected. Halting requests for 10 minutes: ResponseError('Invalid response, status code: 503 - Data: {"message":"09/20/2022 01:00 ～ 09/20/2022 03:00 (UTC ± 00)","code":5300}')
2022-09-20 01:11:50,455 - Service - INFO - Resetting connection
2022-09-20 01:11:50,455 - Service - INFO - Connecting to Panasonic Comfort Cloud..
2022-09-20 01:11:52,949 - Service - INFO - Shutting down
Traceback (most recent call last):
  File "/app/run.py", line 4, in <module>
    __main__.main()
  File "/app/pcfmqtt/__main__.py", line 42, in main
    s.start()
  File "/app/pcfmqtt/service.py", line 79, in start
    self.connect_to_cc()
  File "/app/pcfmqtt/service.py", line 45, in connect_to_cc
    self._session.login()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 503 - Data: {"message":"09/20/2022 01:00 ～ 09/20/2022 03:00 (UTC ± 00)","code":5300}
```

**Comment by slvwolf** [comment]
Resolved with `v0.4.4`
